### ISSUE TITLE
New Favicon

### ISSUE THREAD

**Issue by deadcoder0904** [lesnitsky/howtodothisinflutter#19]
It confused me which website I was opening as you have used Flutter's logo.

I think it makes sense to change to anything else than that. But I understand it might not be a priority :)

**Comment by stormr1der** [comment]
To change the application icon you should change `pubspec.yaml` in next way:

```yaml
flutter_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
```
After this execute next commands in terminal: 

`flutter pub get`

`flutter pub pub run flutter_launcher_icons:main`
